name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build cc65
      run: |
        git submodule update --init --recursive
        cd cc65
        make
      
    - name: Build all examples
      run: make
